# ----- Build command ----- #
name: build
help: Compiles and builds all scripts

flags:
  - import: src/flags/lang.yml
  - import: src/flags/algo.yml

examples:
  - benchmark build 
  - benchmark build --lang java
